# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/circleci-testing
    docker:
      - image: alpine:edge
    environment:
      GOPATH: /home/circleci/go
    steps:
      - run: apk update
      - run: apk add git
      - checkout

      # - run: echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
      # - run: apk update
      # - run: apk add zig
      - run: ./download_zig.sh 0.7.0
      - run: zig version
      - run: zig env
      - run: apk add jq grep
      - run: ./build_all.sh
      - store_artifacts:
          path: ./zig-cache/bin/
          destination: /artifacts/

      - run: apk add go
      - run: ls -l /artifacts/
      - run: ./make_release.sh
