# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/circleci-testing
    docker:
      - image: golang
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt update
      - run: apt -y upgrade
      - checkout

      # - run: echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
      # - run: apk update
      # - run: apk add zig
      - run: apt -y install xz-utils jq
      - run: ./download_zig.sh 0.7.0
      - run: zig version
      - run: zig env
      - run: ./build_all.sh
      - store_artifacts:
          path: ./zig-cache/bin/
          destination: /artifacts/

      - run: ls -lh
      - run: ls -lh /
      - run: ls -lh /artifacts/
      - run: ./make_release.sh
