# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/circleci-testing
    docker:
      - image: alpine:edge
    steps:
      - run: apk update
      - run: apk add git
      - checkout

      - run: apk add go
      - run: go version
      - run: go env
      - run: go build
      - run: ./circleci-testing

      # - run: echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
      # - run: apk update
      # - run: apk add zig
      - run: apk add wget tar
      - run: wget https://ziglang.org/download/0.7.0/zig-linux-x86_64-0.7.0.tar.xz
      - run: tar -vxf zig-linux-x86_64-0.7.0.tar.xz
      - run: ln -s ./zig-linux-x86_64-0.7.0/zig /bin
      - run: zig version
      - run: zig env
      - run: zig targets
      - run: zig build
      - run: ./zig-cache/bin/circleci-testing
